export class GuestRegist {
    arriveDate: string;
    arriveTime: string;
    roomNo: number;
    name: string;
    nationality: string;
    _id: string;
    currentaddress: string;
    job: string;
    comefrom: string;
    goto: string;
    gotoProvince: string;
    departureDate: string;
    departureTime: string;
    remark: string;
    pax: number;
    company: string;
    roomrate: string;
    abf?: number;
}

export const GuestInhouse: GuestRegist[] =
    [
        {
            arriveDate: "6/7/2018",
            arriveTime: "10:00",
            roomNo: 309,
            name: "วีระชัย ย่อชัย",
            nationality: "ไทย",
            _id: "3 3314 00287 65 2",
            currentaddress: "109 ม.9 ต.โคกม้า อ.ประโคนชัย จ.บุรีรัมย์",
            job: "รับจ้าง",
            comefrom: "บุรีรัมย์",
            goto: "อ.เมือง",
            gotoProvince: "จ.ศรีสะเกษ",
            departureDate: "8/7/18",
            departureTime: "12:00",
            remark: "DJ.I-Bar",
            pax: 2,
            company: "w-in",
            roomrate: "600",
            abf: 2,
        },
        {
            arriveDate: "3/7/2018",
            arriveTime: "12:00",
            roomNo: 211,
            name: "กิตติพงษ์ บัวผัน",
            nationality: "ไทย",
            _id: "1 1114 00287 65 2",
            currentaddress: "52 ม.9 ต.เมือง อ.เมือง จ.อุบลราชธานี",
            job: "รับจ้าง",
            comefrom: "อุบลราชธานี",
            goto: "อ.เมือง",
            gotoProvince: "จ.ศรีสะเกษ",
            departureDate: "8/7/18",
            departureTime: "12:00",
            remark: "",
            pax: 2,
            company: "w-in",
            roomrate: "600",
            abf: 2,
        },
        {
            arriveDate: "6/7/2018",
            arriveTime: "12:10",
            roomNo: 222,
            name: "ปริญญา เจริญรอย",
            nationality: "ไทย",
            _id: "3 6114 00287 65 2",
            currentaddress: "85 ม.13 ต.เมือง อ.เมือง จ.บึงกาฬ",
            job: "รับจ้าง",
            comefrom: "บึงกาฬ",
            goto: "อ.เมือง",
            gotoProvince: "จ.ศรีสะเกษ",
            departureDate: "12/7/18",
            departureTime: "12:00",
            remark: "",
            pax: 1,
            company: "w-in",
            roomrate: "600",
            abf: 1,
        },
        {
            arriveDate: "6/7/2018",
            arriveTime: "12:10",
            roomNo: 445,
            name: "หนุมาน ศรีหราช",
            nationality: "ไทย",
            _id: "3 6114 00287 65 2",
            currentaddress: "85 ม.13 ต.เมือง อ.เมือง จ.บึงกาฬ",
            job: "รับจ้าง",
            comefrom: "บึงกาฬ",
            goto: "อ.เมือง",
            gotoProvince: "จ.ศรีสะเกษ",
            departureDate: "12/7/18",
            departureTime: "12:00",
            remark: "",
            pax: 2,
            company: "w-in",
            roomrate: "Comp",
            abf: 2,
        },
        {
            arriveDate: "5/7/2018",
            arriveTime: "12:10",
            roomNo: 525,
            name: "เฉลิมเกียรติ ทินกร",
            nationality: "ไทย",
            _id: "3 4114 00287 65 2",
            currentaddress: "123/15 ม.13 ต.เมือง อ.เมือง จ.อุบลราชธานี",
            job: "รับจ้าง",
            comefrom: "อุบลราชธานี",
            goto: "อ.เมือง",
            gotoProvince: "จ.ศรีสะเกษ",
            departureDate: "12/7/18",
            departureTime: "12:00",
            remark: "",
            pax: 2,
            company: "w-in",
            roomrate: "Comp",
            abf: 2,
        },
        {
            arriveDate: "",
            arriveTime: "",
            roomNo: 422,
            name: "ooo",
            nationality: "",
            _id: "",
            currentaddress: "",
            job: "",
            comefrom: "",
            goto: "",
            gotoProvince: "",
            departureDate: "",
            departureTime: "",
            remark: "",
            pax: null,
            company: "",
            roomrate: null,
            abf: null,
        },
        {
            arriveDate: "",
            arriveTime: "",
            roomNo: 220,
            name: "ห้องบัญชี",
            nationality: "",
            _id: "",
            currentaddress: "",
            job: "",
            comefrom: "",
            goto: "",
            gotoProvince: "",
            departureDate: "",
            departureTime: "",
            remark: "",
            pax: null,
            company: "",
            roomrate: null,
            abf: null,
        },
        {
            arriveDate: "",
            arriveTime: "",
            roomNo: 221,
            name: "ห้องแม่บ้าน",
            nationality: "",
            _id: "",
            currentaddress: "",
            job: "",
            comefrom: "",
            goto: "",
            gotoProvince: "",
            departureDate: "",
            departureTime: "",
            remark: "",
            pax: null,
            company: "",
            roomrate: null,
            abf: null,
        },
        {
            arriveDate: "6/7/2018",
            arriveTime: "10:00",
            roomNo: 515,
            name: "เวทิศ กาญจนา",
            nationality: "ไทย",
            _id: "3 3314 00287 65 2",
            currentaddress: "109 ม.9 ต.โคกม้า อ.ประโคนชัย จ.บุรีรัมย์",
            job: "รับจ้าง",
            comefrom: "บุรีรัมย์",
            goto: "อ.เมือง",
            gotoProvince: "จ.ศรีสะเกษ",
            departureDate: "8/7/18",
            departureTime: "12:00",
            remark: "DJ.I-Bar",
            pax: 2,
            company: "w-in",
            roomrate: "1500",
            abf: 2,
        },
    ]

export const GuestRegister: GuestRegist[] =
    [
        {
            arriveDate: "6/7/2018",
            arriveTime: "10:00",
            roomNo: 309,
            name: "วีระชัย ย่อชัย",
            nationality: "ไทย",
            _id: "3 3314 00287 65 2",
            currentaddress: "109 ม.9 ต.โคกม้า อ.ประโคนชัย จ.บุรีรัมย์",
            job: "รับจ้าง",
            comefrom: "บุรีรัมย์",
            goto: "อ.เมือง",
            gotoProvince: "จ.ศรีสะเกษ",
            departureDate: "8/7/18",
            departureTime: "12:00",
            remark: "DJ.I-Bar",
            pax: 2,
            company: "w-in",
            roomrate: "600",
            abf: 2,
        },
        {
            arriveDate: "3/7/2018",
            arriveTime: "12:00",
            roomNo: 211,
            name: "กิตติพงษ์ บัวผัน",
            nationality: "ไทย",
            _id: "1 1114 00287 65 2",
            currentaddress: "52 ม.9 ต.เมือง อ.เมือง จ.อุบลราชธานี",
            job: "รับจ้าง",
            comefrom: "อุบลราชธานี",
            goto: "อ.เมือง",
            gotoProvince: "จ.ศรีสะเกษ",
            departureDate: "8/7/18",
            departureTime: "12:00",
            remark: "",
            pax: 2,
            company: "w-in",
            roomrate: "600",
            abf: 2,
        },
        {
            arriveDate: "6/7/2018",
            arriveTime: "12:10",
            roomNo: 222,
            name: "ปริญญา เจริญรอย",
            nationality: "ไทย",
            _id: "3 6114 00287 65 2",
            currentaddress: "85 ม.13 ต.เมือง อ.เมือง จ.บึงกาฬ",
            job: "รับจ้าง",
            comefrom: "บึงกาฬ",
            goto: "อ.เมือง",
            gotoProvince: "จ.ศรีสะเกษ",
            departureDate: "12/7/18",
            departureTime: "12:00",
            remark: "",
            pax: 1,
            company: "w-in",
            roomrate: "600",
            abf: 1,
        },
        {
            arriveDate: "6/7/2018",
            arriveTime: "12:10",
            roomNo: 445,
            name: "หนุมาน ศรีหราช",
            nationality: "ไทย",
            _id: "3 6114 00287 65 2",
            currentaddress: "85 ม.13 ต.เมือง อ.เมือง จ.บึงกาฬ",
            job: "รับจ้าง",
            comefrom: "บึงกาฬ",
            goto: "อ.เมือง",
            gotoProvince: "จ.ศรีสะเกษ",
            departureDate: "12/7/18",
            departureTime: "12:00",
            remark: "",
            pax: 2,
            company: "w-in",
            roomrate: "800",
            abf: 2,
        },
        {
            arriveDate: "5/7/2018",
            arriveTime: "12:10",
            roomNo: 525,
            name: "เฉลิมเกียรติ ทินกร",
            nationality: "ไทย",
            _id: "3 4114 00287 65 2",
            currentaddress: "123/15 ม.13 ต.เมือง อ.เมือง จ.อุบลราชธานี",
            job: "รับจ้าง",
            comefrom: "อุบลราชธานี",
            goto: "อ.เมือง",
            gotoProvince: "จ.ศรีสะเกษ",
            departureDate: "12/7/18",
            departureTime: "12:00",
            remark: "",
            pax: 2,
            company: "w-in",
            roomrate: "Comp",
            abf: 2,
        },
        {
            arriveDate: "6/7/2018",
            arriveTime: "10:00",
            roomNo: 515,
            name: "เวทิศ กาญจนา",
            nationality: "ไทย",
            _id: "3 3314 00287 65 2",
            currentaddress: "109 ม.9 ต.โคกม้า อ.ประโคนชัย จ.บุรีรัมย์",
            job: "รับจ้าง",
            comefrom: "บุรีรัมย์",
            goto: "อ.เมือง",
            gotoProvince: "จ.ศรีสะเกษ",
            departureDate: "8/7/18",
            departureTime: "12:00",
            remark: "DJ.I-Bar",
            pax: 2,
            company: "w-in",
            roomrate: "1500",
            abf: 2,
        },
    ]

